### ISSUE TITLE
3D Gaussian Splatting Viewer added to nerfstudio

### ISSUE THREAD

**Issue by XinyueZ** [cvlab-epfl/gaussian-splatting-web#11]
https://neuralradiancefields.io/3d-gaussian-splatting-viewer-added-to-nerfstudio/

**Comment by jatentaki** [comment]
Thanks. This afaik works by running the original code on Nvidia gpu and streaming the results to the browser, so it requires one to run an expensive server. In contrast, my implementation works fully client side so it can be deployed with a simple static file server like GitHub pages.
