### ISSUE TITLE
Fix 3rd degree spherical harmonics

### ISSUE THREAD

**Issue by jatentaki** [cvlab-epfl/gaussian-splatting-web#2]
3rd degree spherical harmonic coefficients are [currently ignored](https://github.com/cvlab-epfl/gaussian-splatting-web/blob/32664fa7ea797501da110d4ee4d211a245511a65/src/shaders.ts#L48) due to a bug which appears to be either caused by memory layout issues or straight up WebGPU bug.

**Comment by johnryan465** [comment]
@jatentaki I don't get a black screen when uncommenting the spherical harmonics, but I do get incorrect values. There is a mentioing of dividing by 10 in the source code, what is the purpose of that?

**Comment by jatentaki** [comment]
What do you mean by incorrect values? My screen is not exactly pitch black, but mostly black with several white blobs, similar to this: ![image](https://pbs.twimg.com/media/F4PHyksXkAADaYp?format=png&name=900x900)
Is it similar for you?

Regarding division by 10, I was considering two possibilities: a numerical overflow or a memory corruption bug (improperly serializing data into buffers and reading trash). If I use all 7 components of the 3rd order SH, I get what you see above. My logic is as follows:
1. If I use the components 1-3, it's fine (colors are slightly off but that's to be expected without using all components). If I use the components 4-7, it's fine. Conclusion: it does not seem to be memory corruption - all components individually lead to sane results.
2. Test for overflow: since using 1-3 is fine and using 4-7 is fine, using their sum divided by 10 should also be fine. But it's not... Which seems to rule out overflow issues.

So the two obvious culprits seem rules out, which is why I am saying this may be a webGPU implementation bug in chromium. Does that make sense? Now that the code is out and available I may try to open a ticket with DAWN developers, previously it was very difficult to make a self-contained reproduction case.

**Comment by jatentaki** [comment]
Fixed by #18
