### ISSUE TITLE
Controls are vertically flipped

### ISSUE THREAD

**Issue by andresrommier** [cvlab-epfl/gaussian-splatting-web#7]
Spent some time debugging trying to find the largest rendering bottle neck and I can confirm it is the gaussian sorting.

Another option to the GPU compute I think would be to create a BVH data structure or another similar data structure like an octree (to sort the Gaussians in blocks).

For the BVH I think you could use https://github.com/gkjohnson/three-mesh-bvh

After commenting out the sorting code (no real Gaussian splatting but useful to see what's the best performance we could get) the controls with the mouse feel smoother but helped me notice that the vertical dragging feels inverted.

**Comment by jatentaki** [comment]
You're right about dragging, will fix in next release.

**Comment by jatentaki** [comment]
Fixed in #10
