### ISSUE TITLE
No frustum culling implemented

### ISSUE THREAD

**Issue by andresrommier** [cvlab-epfl/gaussian-splatting-web#8]
After playing a bit more with the viewer I noticed that during sorting the code is using all the gaussians on the file.

I think a significant speed up can be achieved just by using the Tiled Frustum culling approach mentioned in the paper.

For large scenes where a significant part of the content can fall outside of  the camera's field of view this can become critical.

**Comment by jatentaki** [comment]
You're right but I doubt if CPU sorting can even achieve good enough results. There's an [alternative project](https://www.linkedin.com/posts/jcerveny_working-on-a-webgl-renderer-for-gaussian-activity-7100553206014849024-VW9h)  where they run a web assembly sort in a webworker thread and seem to achieve decent results. My preferred solution would be to implement a GPU sort but I can't promise any timeline for that.

**Comment by jatentaki** [comment]
With #10 I landed a GPU sort. This improves the FPS significantly but makes it even more tricky (and less beneficial) to include frustum culling.
